// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbl0B7m9d5Bu0gd_AhbW0oOsNuFZ1_Klk',
    appId: '1:62616774239:web:5a113184e58a7f5b935dea',
    messagingSenderId: '62616774239',
    projectId: 'quotealineapp-9ac36',
    authDomain: 'quotealineapp-9ac36.firebaseapp.com',
    storageBucket: 'quotealineapp-9ac36.appspot.com',
    measurementId: 'G-CFLTTEMFMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV48j8J5LfoEJaKOEMIdckuQgyPP9u7Po',
    appId: '1:62616774239:android:d779ba8a06e472b7935dea',
    messagingSenderId: '62616774239',
    projectId: 'quotealineapp-9ac36',
    storageBucket: 'quotealineapp-9ac36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW5Fjp4J4olGJM53V0nZOlixpkOMnkCMw',
    appId: '1:62616774239:ios:35621506e29c636d935dea',
    messagingSenderId: '62616774239',
    projectId: 'quotealineapp-9ac36',
    storageBucket: 'quotealineapp-9ac36.appspot.com',
    iosClientId: '62616774239-hv5dh9kghgp9jlavd34hti3s5pf0gsd9.apps.googleusercontent.com',
    iosBundleId: 'com.example.quotalineApplication',
  );
}
